### ISSUE TITLE
Circular import exception when running  prepare_inserts_data.py

### ISSUE THREAD

**Issue by rbskpoly** [leddartech/pioneer.das.api#9]
The following exception is being thrown:

python3 prepare_inserts_data.py --cfg=configs/pixell_to_box3d.yml

/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "prepare_inserts_data.py", line 1, in <module>
    from object_detection_pixell.dataloader import LeddartechDataset
  File "/home/rogerb/Documents/artp/sw/object_detection_pixell/object_detection_pixell/dataloader.py", line 1, in <module>
    from object_detection_pixell.utils import filter_training_frames
  File "/home/rogerb/Documents/artp/sw/object_detection_pixell/object_detection_pixell/utils/__init__.py", line 3, in <module>
    from .various import *
  File "/home/rogerb/Documents/artp/sw/object_detection_pixell/object_detection_pixell/utils/various.py", line 1, in <module>
    from pioneer.das.api.samples import Box3d
  File "/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/samples/__init__.py", line 1, in <module>
    from pioneer.das.api.samples.annotations import *
  File "/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/samples/annotations/__init__.py", line 2, in <module>
    from pioneer.das.api.samples.annotations.box_3d import Box3d
  File "/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/samples/annotations/box_3d.py", line 5, in <module>
    from pioneer.das.api.samples.sample import Sample
  File "/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/samples/sample.py", line 4, in <module>
    from pioneer.das.api.egomotion import EgomotionProvider
  File "/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/egomotion/__init__.py", line 2, in <module>
    from pioneer.das.api.egomotion.carla_egomotion_provider import CarlaEgomotionProvider
  File "/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/egomotion/carla_egomotion_provider.py", line 3, in <module>
    from pioneer.das.api.datasources                   import DatasourceWrapper
  File "/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/datasources/__init__.py", line 4, in <module>
    from pioneer.das.api.datasources.virtual_datasources.virtual_datasource import VirtualDatasource
  File "/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/datasources/virtual_datasources/__init__.py", line 2, in <module>
    from pioneer.das.api.datasources.virtual_datasources.bounding_box_metadata import BoundingBoxMetadata
  File "/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/datasources/virtual_datasources/bounding_box_metadata.py", line 2, in <module>
    from pioneer.das.api.samples import Sample
ImportError: cannot import name 'Sample' from partially initialized module 'pioneer.das.api.samples' (most likely due to a circular import) (/home/rogerb/.local/lib/python3.8/site-packages/pioneer/das/api/samples/__init__.py)

The following pip packages are being used:
pioneer-common          1.3.1                
pioneer-common-gui      1.4.0                
pioneer-das-api         1.4.3                
pioneer-das-view        1.4.0

**Comment by jeanlucdeziel-leddartech** [comment]
The fix is on its way. I'll update you once it is live.

**Comment by rbskpoly** [comment]
Awesome! Thanks!

**Comment by jeanlucdeziel-leddartech** [comment]
It should be fixed with version 1.4.4

**Comment by rbskpoly** [comment]
Confirmed that prepare_inserts_data.py now works and runs to completion. Thanks for the prompt response!
